name: pi_block
description: "Application to manage Pi-Hole instance"
publish_to: 'none'
version: 1.2.0+4

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^1.1.1
  flutter_json_view: ^1.1.5
  flutter_randomcolor: ^1.0.18
  font_awesome_flutter: ^10.12.0
  go_router: ^16.3.0
  google_fonts: ^6.3.2
  http: ^1.5.0
  intl: ^0.20.2
  logging: ^1.3.0
  pager: ^0.0.6
  provider: ^6.1.5+1
  rounded_expansion_tile: ^0.0.13
  shared_preferences: ^2.5.3
  timeago: ^3.7.1
  circle_time_progress: ^0.0.2
  flutter_timer_countdown: ^1.0.7
  multi_value_listenable_builder: ^0.0.2
  flutter_advanced_switch: ^3.1.0
  flutter_switch: ^0.3.2
  package_info_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  icons_launcher: ^3.0.3

flutter:
  uses-material-design: true