default_platform(:android)

platform :android do

  desc "Upload new build to Internal testing"
  lane :internal do
    version_code = ENV["VERSION_CODE"]
    upload_to_play_store(
      track: "internal",
      aab: ENV["AAB_PATH"] || "build/app/outputs/bundle/release/app-release.aab",
      version_code: version_code,
      
      # Enable changelog upload
      skip_upload_metadata: false,
      
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

  desc "Promote build from Internal → Alpha"
  lane :alpha do
    version_code = ENV["VERSION_CODE"]
    upload_to_play_store(
      track: "internal",
      track_promote_to: "alpha",
      version_code: version_code,
      skip_upload_metadata: true,
      skip_upload_changelogs: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

end

platform :ios do
  desc "Deploy iOS"
  lane :deploy do
    # later: TestFlight / App Store
  end
end
